apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-database-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  # root password is required to be specified
  ROOT_PASSWORD: cFNHUVl3YmxrYUtrNFk2aDJtWDU3OExoWDZEejdKbmhBdktHb25uSkdZR1NUWGNTZ2FFNHRUNVVIS1pjS2RCUA==
  # a user name to be created, not required
  USER: b3JkZXJtYXRpYw==
  # a password for user, not required
  PASSWORD: cFNHUVl3YmxrYUtrNFk2aDJtWDU3OExoWDZEejdKbmhBdktHb25uSkdZR1NUWGNTZ2FFNHRUNVVIS1pjS2RCUA==
  # a name for database that will be created, not required
  DATABASE: b3JkZXJtYXRpYw==